name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        
      - name: Unit tests
        run: composer run phpunit
          
      - name: Static analysis
        run: composer run-script phpstan
        
      - name: Mutation tests
        run: composer run-script infection-ci
